### ISSUE TITLE
Overflow menu header conflicts with existing panel header

### ISSUE THREAD

**Issue by Osmose** [mozilla/price-tracker#213]
When the toolbar icon is put in the overflow menu, the popup panel has an extra header added to it:

<img width="404" alt="screen shot 2018-10-25 at 9 53 22 am" src="https://user-images.githubusercontent.com/193106/47517216-5e81c380-d83c-11e8-9894-1a15fd2e205c.png">

Currently, I've been putting the add-on title in the titlebar, but it looks kinda silly in that screenshot.

The quickest fix is probably to change the title in the titlebar so it doesn't conflict. Longer term we may want to file a followup that displays a slightly-different UI in this mode, or changes the UI to not conflict.

Assigning to @chuckharmston to chose a better title.

**Comment by chuckharmston** [comment]
Let's go with `Products`.
